ItemNames: ; 472b (1:472b)
	db "MÆGESTERBEALL@"
	db "OFERBEALL@"
	db "MICELBEALL@"
	db "ÞYRSBEALL@"
	db "BURGCARTE@"
	db "FARHWEOL@"
	db "?????@"
	db "FARUBEALL@"
	db "POCCAUDEX@"
	db "MONASTAN@"
	db "TIRIACA@"
	db "BYRNE LÆCEWYRT@"
	db "IS LÆCEWYRT@"
	db "AWACNUNG@"
	db "LAMA LÆCEWYRT@"
	db "EDWYRPUNG@"
	db "FULLDRENC@"
	db "OFERDRENC@"
	db "MICELDRENC@"
	db "DRENC@"
	db "CARRBEAG@"
	db "ÞEOTEBEAG@"
	db "THUNORBEAG@"
	db "REGNBOGABEAG@"
	db "FERHÐBEAG@"
	db "MERSCBEAG@"
	db "FYRBEORGBEAG@"
	db "EORÐEBEAG@"
	db "SWICERAP@"
	db "WIÐDRIFUNG@"
	db "DIEGOL GLÆR@"
	db "FYRSTAN@"
	db "ÞUNORSTAN@"
	db "WÆTERSTAN@"
	db "HÆLHEBBUNG@"
	db "ÆGHWIT@"
	db "ISERN@"
	db "COL@"
	db "CEALC@"
	db "SWETMETE@"
	db "BUC GRAFEN@"
	db "GEWEND GRAFEN@"
	db "DIEGLU KÆG@"
	db "?????@"
	db "FARHWEOLCARTE@"
	db "GELOMLÆCUNG@"
	db "LEAFSTAN@"
	db "CARTEKÆG@"
	db "CLYMPRE@"
	db "MÆÐHEBBUNG@"
	db "POCCADOCCA@"
	db "FULL LÆCEWYRT@"
	db "EDCWICIAN@"
	db "FULL EDCWICIAN@"
	db "GEBYRDWEARD@"
	db "MICEL DRIFUNG@"
	db "FULL DRIFUNG@"
	db "GRIM HITTUNG@"
	db "MYNET@"
	db "FERSC WÆTER@"
	db "EALU@"
	db "MEDU@"
	db "SCIPCARTE@"
	db "GYLDENE TEÐ@"
	db "GESWIÐRUNG@"
	db "EALGUNG@"
	db "EFSTUNG@"
	db "SUNDORHEBBUNG@"
	db "MYNETBOX@"
	db "ACes PÆCCA@"
	db "ÞINGFINDEND@"
	db "SYLF WLATUNG@"
	db "POCCAHWISTLE@"
	db "UPTYGE KÆG@"
	db "EALLCUNNUNG@"
	db "EALD RODD@"
	db "GOD RODD@"
	db "MICEL RODD@"
	db "MÆÐHEBBUNG@"
	db "MM HELP@"
	db "MM WYRP@"
	db "MM HELPUNG@"
	db "MM FYLLUNG@"
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
