TrainerNames: ; 399ff (e:59ff)
	db "GEOGUÐ@"
	db "BUDDAFONGERE@"
	db "MÆGDENCILD@"
	db "FLOTMAN@"
	db "TELDERE@"
	db "TELDESTRE@"
	db "ÞYRSWINE@"
	db "SEARUMANN@"
	db "FEÐERE@"
	db "HWEOLFARA@"
	db "BURGBRECA@"
	db "WEORCWITA@"
	db "GEDWIMERE@"
	db "FISCERE@"
	db "SWIMMEND@"
	db "CALUMANN@"
	db "TÆFLERE@"
	db "ÆLFSCIENE@"
	db "GALDERE@"
	db "SCOP@"
	db "GEDWIMERE@"
	db "TAMNIA@"
	db "FUGOLHIERDE@"
	db "BLÆCBELT@"
	db "GEWINNA 1@"
	db "MGSTR.AC@"
	db "ÞEGEN@"
	db "UÐWITA@"
	db "SWEGEN@"
	db "ROCCA@"
	db "MICELRÆRERE@"
	db "MICELRÆRESTRE@"
	db "SIGEBYRNE@"
	db "BROCC@"
	db "MISTFLÆD@"
	db "ÞORÞEGN@"
	db "ANRICEN@"
	db "COGA@"
	db "BÆLRÆD@"
	db "SÆFERN@"
	db "EORL@"
	db "GEWINNA 2@"
	db "GEWINNA 3@"
	db "SCAÐI@"
	db "HALGIESTRE@"
	db "GREOSAÞRYÐ@"
	db "WIGLAF@"
